# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03bf651f1bcbd809b1c89fd56d65677193e3ceb4d86e20aa6927e9955e65bc8dd5b412bba97757ea748fa86f10d65feddff579dd8f74fa2c0965a71f8cf14b62

test:
  secret_key_base: c943c88d4ae9d16dc45c03553a79377dfb1bb7e179fe2e37e4788e1a6f4ff34bfdddb23c3ad0ee0a694eb4182afbd1df61a24044145a74b4ad302a27395b6e69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
